### ISSUE TITLE
Add default titles to plot depending on object/quant it is plotting

### ISSUE THREAD

**Issue by ChrKo1** [flr/ggplotFL#14]
Pretty much what it says in the title

**Comment by iagomosqueira** [comment]
Is this for the FLStock plot? That one is based on the FLQuants returned by metrics(), so the names and units are shown on the facet panels. Or for a single FLQuant? In that case the lot method cannot know what is being plotted.

A title can always be added, for example

```
plot(catch(ple4)) + ggtitle("Catch (t)")
```
